### ISSUE TITLE
setspawn (bounds)

### ISSUE THREAD

**Issue by teachMeHowToYeet** [ShevchikUnsupportedProjects/TNTRun#26]
Its not working properly

**Comment by KC-7** [comment]
Be more specific; 
- What exactly isn't working?
- What errors/indicators do you get?
- What plugins/server version/other info do you have?

**Comment by teachMeHowToYeet** [comment]
Basically when i set bounds i do like in world edit first on top corner second on bottom opposite corner then i do /tntsetup bounds when i do /tntsetup setspawn it says it needs to be in bounds ?

**Comment by Shevchik** [comment]
Make sure you accounted for height.

**Comment by teachMeHowToYeet** [comment]
I don't really get what you mean could make an example like a vid or something

**Comment by Shevchik** [comment]
Bound is full cube. Which means that y is accounted for in bounds check too. So make sure you expanded your selection vertically too.

**Comment by teachMeHowToYeet** [comment]
Ummmmm still confused 😂Can you just make a mini tutorial ?

**Comment by KC-7** [comment]
You can find many [tutorial videos on YouTube](https://www.youtube.com/results?search_query=tntrun+tutorial).

For clarity, however, what @Shevchik was saying is: make sure the corners of your cube are at different heights. If they are the same height, then you get a square, not a cube.
